import type { SubtitleEntry, TranslatedEntry } from "@/types";

export interface CaptionTrack {
  languageCode: string;
  languageName: string;
  baseUrl: string;
  isAutoGenerated: boolean;
}

export function createSubtitleUrl(
  track: CaptionTrack,
  videoId?: string,
): string {
  const params = new URLSearchParams({
    baseUrl: track.baseUrl,
    lang: track.languageCode,
    languageName: track.languageName,
  });

  if (videoId) params.set("videoId", videoId);
  return `/api/youtube/subtitle?${params.toString()}`;
}

export function parseSrtToEntries(srt: string): SubtitleEntry[] {
  const blocks = srt.trim().split(/\n\s*\n/);
  return blocks
    .map((block) => {
      const lines = block.trim().split("\n");
      if (lines.length < 3) return null;

      const index = parseInt(lines[0], 10);
      const timeMatch = lines[1].match(
        /(\d{2}:\d{2}:\d{2},\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2},\d{3})/,
      );
      if (!timeMatch) return null;

      return {
        index,
        startTime: timeMatch[1],
        endTime: timeMatch[2],
        text: lines.slice(2).join("\n").trim(),
        startMs: srtTimeToMs(timeMatch[1]),
        endMs: srtTimeToMs(timeMatch[2]),
      };
    })
    .filter(Boolean) as SubtitleEntry[];
}

function srtTimeToMs(time: string): number {
  const [hours, minutes, remainder] = time.split(":");
  const [seconds, milliseconds] = remainder.split(",");
  return (
    parseInt(hours) * 3600000 +
    parseInt(minutes) * 60000 +
    parseInt(seconds) * 1000 +
    parseInt(milliseconds)
  );
}

export async function readTranslateStream(
  response: Response,
): Promise<TranslatedEntry[]> {
  const reader = response.body?.getReader();
  if (!reader) throw new Error("无法读取服务端响应");

  const decoder = new TextDecoder();
  let buffer = "";
  let resultData: { translatedEntries?: TranslatedEntry[] } | null = null;

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;

    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split("\n");
    buffer = lines.pop() || "";

    for (const line of lines) {
      if (!line.trim()) continue;
      try {
        const event = JSON.parse(line);
        if (event.type === "complete" && event.translatedEntries) {
          resultData = event;
        }
      } catch {
        continue;
      }
    }
  }

  if (!resultData?.translatedEntries) {
    throw new Error("翻译服务未返回结果");
  }
  return resultData.translatedEntries;
}
