import { NextRequest, NextResponse } from "next/server";
import { getInnertube, extractVideoId } from "@/lib/youtube";

export const runtime = "nodejs";

interface CaptionTrackInfo {
  languageCode: string;
  languageName: string;
  baseUrl: string;
  isAutoGenerated: boolean;
}

interface VideoFormatInfo {
  itag: number;
  qualityLabel: string;
  container: string;
  hasVideo: boolean;
  hasAudio: boolean;
  bitrate: number;
  contentLength?: number;
}

/**
 * 依次尝试不同客户端获取视频信息，直到成功为止。
 * 不同客户端对 bot 检测的严格程度不同，TV 和 IOS 通常更宽松。
 */
async function fetchVideoInfo(innertube: Awaited<ReturnType<typeof getInnertube>>, videoId: string) {
  const clients = ["TV", "IOS", "ANDROID", "WEB"] as const;
  let lastError: unknown = null;

  for (const client of clients) {
    try {
      const info = await innertube.getBasicInfo(videoId, { client });
      const playability = info.playability_status;
      if (playability && playability.status === "OK") {
        return info;
      }
      lastError = new Error(playability?.reason || `客户端 ${client} 无法播放该视频`);
    } catch (error) {
      lastError = error;
    }
  }

  throw lastError;
}

export async function GET(request: NextRequest) {
  const url = request.nextUrl.searchParams.get("url");

  if (!url) {
    return NextResponse.json({ error: "请提供 YouTube 视频链接" }, { status: 400 });
  }

  const videoId = extractVideoId(url);
  if (!videoId) {
    return NextResponse.json({ error: "无效的 YouTube 视频链接" }, { status: 400 });
  }

  try {
    const innertube = await getInnertube();
    const info = await fetchVideoInfo(innertube, videoId);

    const basic = info.basic_info;

    const captionTracks: CaptionTrackInfo[] = (
      info.captions?.caption_tracks ?? []
    ).map((track) => ({
      languageCode: track.language_code,
      languageName: track.name?.toString() || track.language_code,
      baseUrl: track.base_url,
      isAutoGenerated: track.kind === "asr",
    }));

    const streamingData = info.streaming_data;
    const formats: VideoFormatInfo[] = (streamingData?.formats ?? [])
      .map((f) => ({
        itag: f.itag,
        qualityLabel: f.quality_label || "unknown",
        container: f.mime_type?.split("/")[1]?.split(";")[0] || "mp4",
        hasVideo: f.has_video,
        hasAudio: f.has_audio,
        bitrate: f.bitrate || 0,
        contentLength: f.content_length,
      }))
      .sort((a, b) => b.bitrate - a.bitrate);

    const audioFormats: VideoFormatInfo[] = (streamingData?.adaptive_formats ?? [])
      .filter((f) => f.has_audio && !f.has_video)
      .map((f) => ({
        itag: f.itag,
        qualityLabel: `${f.audio_quality || "?"}`,
        container: f.mime_type?.split("/")[1]?.split(";")[0] || "mp4",
        hasVideo: false,
        hasAudio: true,
        bitrate: f.bitrate || 0,
        contentLength: f.content_length,
      }))
      .sort((a, b) => b.bitrate - a.bitrate);

    const thumbnails = basic.thumbnail ?? [];
    const thumbnail =
      thumbnails.length > 0 ? thumbnails[thumbnails.length - 1].url : "";

    return NextResponse.json({
      videoId: basic.id,
      title: basic.title,
      author: basic.author || basic.channel?.name || "",
      duration: String(basic.duration || 0),
      thumbnail,
      viewCount: basic.view_count,
      captionTracks,
      formats,
      audioFormats,
    });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "获取视频信息失败";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
