"use client";

import { useCallback, useState } from "react";
import type { SubtitleEntry, TranslatedEntry } from "@/types";
import { Button, Input, toast } from "@heroui/react";
import { AlertCircle, Captions, Download, Link } from "lucide-react";
import { getApiKeyHeaders } from "@/lib/api-key-storage";
import YouTubeMediaDownloads, { type MediaFormat } from "@/components/YouTubeMediaDownloads";
import YouTubeVideoSummary from "@/components/YouTubeVideoSummary";
import { YouTubeAccessNotice } from "@/components/YouTubeStatusNotice";
interface CaptionTrack {
  languageCode: string;
  languageName: string;
  baseUrl: string;
  isAutoGenerated: boolean;
}

interface VideoInfo {
  videoId: string;
  title: string;
  author: string;
  duration: string;
  thumbnail: string;
  publishedAt?: string | null;
  viewCount?: number | null;
  captionTracks: CaptionTrack[];
  formats: MediaFormat[];
  audioFormats: MediaFormat[];
  accessLimited?: boolean;
  accessMessage?: string;
}

interface YouTubeDownloaderProps {
  onSubtitleLoad: (original: SubtitleEntry[], translated: TranslatedEntry[]) => void;
  onError: (message: string) => void;
}
function parseSrtToEntries(srt: string): SubtitleEntry[] {
  const blocks = srt.trim().split(/\n\s*\n/);
  return blocks
    .map((block) => {
      const lines = block.trim().split("\n");
      if (lines.length < 3) return null;
      const index = parseInt(lines[0], 10);
      const timeMatch = lines[1].match(/(\d{2}:\d{2}:\d{2},\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2},\d{3})/);
      if (!timeMatch) return null;
      const text = lines.slice(2).join("\n").trim();
      return {
        index,
        startTime: timeMatch[1],
        endTime: timeMatch[2],
        text,
        startMs: srtTimeToMs(timeMatch[1]),
        endMs: srtTimeToMs(timeMatch[2]),
      };
    })
    .filter(Boolean) as SubtitleEntry[];
}
function srtTimeToMs(time: string): number {
  const [h, m, rest] = time.split(":");
  const [s, ms] = rest.split(",");
  return parseInt(h) * 3600000 + parseInt(m) * 60000 + parseInt(s) * 1000 + parseInt(ms);
}
async function readTranslateStream(response: Response): Promise<TranslatedEntry[]> {
  const reader = response.body?.getReader();
  if (!reader) throw new Error("无法读取服务端响应");
  const decoder = new TextDecoder();
  let buffer = "";
  let resultData: { translatedEntries?: TranslatedEntry[] } | null = null;
  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split("\n");
    buffer = lines.pop() || "";
    for (const line of lines) {
      if (!line.trim()) continue;
      try {
        const event = JSON.parse(line);
        if (event.type === "complete" && event.translatedEntries) {
          resultData = event;
        }
      } catch {
        // ignore
      }
    }
  }
  if (!resultData?.translatedEntries) {
    throw new Error("翻译服务未返回结果");
  }
  return resultData.translatedEntries;
}
export default function YouTubeDownloader({ onSubtitleLoad, onError }: YouTubeDownloaderProps) {
  const [url, setUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const [videoInfo, setVideoInfo] = useState<VideoInfo | null>(null);
  const [downloadingSubtitle, setDownloadingSubtitle] = useState<string | null>(null);
  const [loadingToEditor, setLoadingToEditor] = useState(false);
  const [loadingToEditorStatus, setLoadingToEditorStatus] = useState("");

  const handleFetch = useCallback(async () => {
    const trimmed = url.trim();
    if (!trimmed) return;
    setLoading(true);
    setVideoInfo(null);
    onError("");
    try {
      const response = await fetch(`/api/youtube/info?url=${encodeURIComponent(trimmed)}`);
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || "获取视频信息失败");
      setVideoInfo(data);
      if (data.accessLimited) {
        toast.warning("已加载视频基础信息", {
          description: "YouTube 暂时限制了字幕和媒体访问。",
        });
      } else {
        toast.success("视频信息解析成功");
      }
    } catch (error: unknown) {
      onError(error instanceof Error ? error.message : "获取视频信息失败");
    } finally {
      setLoading(false);
    }
  }, [url, onError]);

  const handleLoadSubtitleToEditor = useCallback(
    async (track: CaptionTrack) => {
      setLoadingToEditor(true);
      setLoadingToEditorStatus("正在下载字幕...");
      onError("");
      try {
        const response = await fetch(
          `/api/youtube/subtitle?baseUrl=${encodeURIComponent(track.baseUrl)}&lang=${track.languageCode}`,
        );
        const data = await response.json();
        if (!response.ok) throw new Error(data.error || "字幕下载失败");
        const entries = parseSrtToEntries(data.srtContent);
        if (entries.length === 0) throw new Error("字幕内容为空");
        setLoadingToEditorStatus(`正在翻译 ${entries.length} 条字幕...`);
        const translateResponse = await fetch("/api/process", {
          method: "POST",
          headers: getApiKeyHeaders({ "Content-Type": "application/json" }),
          body: JSON.stringify({
            type: "srt",
            srtContent: data.srtContent,
            autoTranslate: true,
            sourceLanguage: "auto",
          }),
        });
        if (!translateResponse.ok) {
          const err = await translateResponse.json().catch(() => null);
          throw new Error(err?.error || "自动翻译失败");
        }
        const translated = await readTranslateStream(translateResponse);
        onSubtitleLoad(entries, translated);
        toast.success("字幕已加载到编辑器", {
          description: `共 ${entries.length} 条字幕，自动翻译已经完成。`,
        });
      } catch (error: unknown) {
        onError(error instanceof Error ? error.message : "字幕加载失败");
      } finally {
        setLoadingToEditor(false);
        setLoadingToEditorStatus("");
      }
    },
    [onSubtitleLoad, onError],
  );

  const handleDownloadSubtitle = useCallback(
    async (track: CaptionTrack) => {
      setDownloadingSubtitle(track.languageCode);
      onError("");
      try {
        const response = await fetch(
          `/api/youtube/subtitle?baseUrl=${encodeURIComponent(track.baseUrl)}&lang=${track.languageCode}`,
        );
        const data = await response.json();
        if (!response.ok) throw new Error(data.error || "字幕下载失败");
        const blob = new Blob([data.srtContent], { type: "text/plain;charset=utf-8" });
        const a = document.createElement("a");
        a.href = URL.createObjectURL(blob);
        a.download = `${videoInfo?.title || "subtitle"}_${track.languageCode}.srt`;
        document.body.appendChild(a);
        a.click();
        a.remove();
        URL.revokeObjectURL(a.href);
        toast.success("字幕文件已下载");
      } catch (error: unknown) {
        onError(error instanceof Error ? error.message : "字幕下载失败");
      } finally {
        setDownloadingSubtitle(null);
      }
    },
    [videoInfo, onError],
  );

  return (
    <div className="space-y-4">
      <div className="flex gap-2">
        <div className="relative min-w-0 flex-1">
          <Link className="pointer-events-none absolute left-3 top-1/2 z-10 h-4 w-4 -translate-y-1/2 text-teal-500" />
          <Input
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            placeholder="粘贴 YouTube 视频链接..."
            aria-label="YouTube 链接"
            fullWidth
            variant="secondary"
            className="pl-9"
            onKeyDown={(e) => e.key === "Enter" && handleFetch()}
          />
        </div>
        <Button
          variant="primary"
          onPress={handleFetch}
          isPending={loading}
          isDisabled={!url.trim()}
          className="bg-gradient-to-r from-teal-600 to-emerald-600 shrink-0"
        >
          {loading ? "解析中..." : "解析"}
        </Button>
      </div>

      {videoInfo && (
        <div className="fade-in-up space-y-4">
          <YouTubeVideoSummary
            title={videoInfo.title}
            author={videoInfo.author}
            duration={videoInfo.duration}
            thumbnail={videoInfo.thumbnail}
            publishedAt={videoInfo.publishedAt}
            viewCount={videoInfo.viewCount}
          />

          {videoInfo.accessLimited && <YouTubeAccessNotice message={videoInfo.accessMessage} />}

          {!videoInfo.accessLimited && videoInfo.captionTracks.length > 0 && (
            <div>
              <h4 className="mb-2 flex items-center gap-1.5 text-xs font-medium text-gray-600 dark:text-gray-300">
                <Captions className="h-3.5 w-3.5" />
                可用字幕
              </h4>
              <div className="space-y-1.5">
                {videoInfo.captionTracks.map((track) => (
                  <div key={track.languageCode} className="flex items-center justify-between gap-2 rounded-lg border border-gray-200 bg-white px-3 py-2 dark:border-gray-700 dark:bg-gray-900">
                    <div className="min-w-0 flex-1">
                      <span className="text-sm text-gray-800 dark:text-gray-200">{track.languageName}</span>
                      {track.isAutoGenerated && (
                        <span className="ml-2 text-[10px] text-gray-400">自动生成</span>
                      )}
                    </div>
                    <div className="flex items-center gap-1.5 shrink-0">
                      <Button
                        size="sm"
                        variant="secondary"
                        onPress={() => void handleLoadSubtitleToEditor(track)}
                        isDisabled={loadingToEditor || downloadingSubtitle !== null}
                        isPending={loadingToEditor}
                      >
                        <Captions className="h-3.5 w-3.5" />
                        {loadingToEditor ? loadingToEditorStatus || "加载中..." : "加载到编辑器"}
                      </Button>
                      <Button
                        size="sm"
                        variant="ghost"
                        onPress={() => void handleDownloadSubtitle(track)}
                        isDisabled={loadingToEditor || downloadingSubtitle !== null}
                      >
                        <Download className="h-3.5 w-3.5" />
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {!videoInfo.accessLimited && videoInfo.captionTracks.length === 0 && (
            <div className="flex items-center gap-2 rounded-lg border border-amber-500/30 bg-amber-500/10 px-3 py-2 text-xs text-amber-600 dark:text-amber-400">
              <AlertCircle className="h-4 w-4 shrink-0" />
              该视频没有可用的字幕轨道
            </div>
          )}

          {!videoInfo.accessLimited && (
            <YouTubeMediaDownloads
              sourceUrl={url}
              videoInfo={videoInfo}
              onError={onError}
            />
          )}
        </div>
      )}
    </div>
  );
}
